<a href="https://colab.research.google.com/github/LuisOtilioZuniga/Programaci-n-para-anal-tica-descriptiva-y-predictiva/blob/main/Practica4_263349.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# importar toda la biblioteca y se usa un alias
import numpy as np

array_random = np.random.randint(1,11,(2,3, 3))  # Array 3x3 con valores aleatorios entre 1 y 10
print("Array 3x3 con valores aleatorios entre 1 y 10")
print(array_random)
print()

Array 3x3 con valores aleatorios entre 1 y 10
[[[10  8  7]
  [ 5  6  3]
  [ 8  9  9]]

 [[ 1  3  5]
  [ 9  4  7]
  [ 1 10  3]]]



In [9]:
#Sumar 1er bloque con el 2ndo bloque
suma_bloques = array_random[0] + array_random[1]
print("Suma de ambos bloques (3x3):")
print(suma_bloques)
#Restar 1er bloque con el 2ndo bloque
resta_bloques = array_random[0] - array_random[1]
print("Resta de ambos bloques (3x3):")
print(resta_bloques)
#Multiplicar 1er bloque por 2
primer_bloque_x2 = array_random[0] * 2
print("Primer bloque multiplicado por 2:")
print(primer_bloque_x2)
#Multiplicar 1er bloque con el 2ndo bloque
producto_elemento = array_random[0] * array_random[1]
print("Multiplicación elemento a elemento (1er bloque × 2do bloque):")
print(producto_elemento)

Suma de ambos bloques (3x3):
[[11 11 12]
 [14 10 10]
 [ 9 19 12]]
Resta de ambos bloques (3x3):
[[ 9  5  2]
 [-4  2 -4]
 [ 7 -1  6]]
Primer bloque multiplicado por 2:
[[20 16 14]
 [10 12  6]
 [16 18 18]]
Multiplicación elemento a elemento (1er bloque × 2do bloque):
[[10 24 35]
 [45 24 21]
 [ 8 90 27]]
